env:
  browser: true
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  "@typescript-eslint/semi": "off"
  "@typescript-eslint/quotes": "off"
